language: go

# Versions of go that are explicitly supported.
go:
 - 1.4.3
 - 1.5.4
 - 1.6.3
 - tip

# Required for coverage.
before_install:
 - go get golang.org/x/tools/cmd/cover
 - go get github.com/mattn/goveralls

script:
 - go build -a -v ./...
 - diff <(gofmt -d .) <("")
 - go test -v -covermode=count -coverprofile=coverage.out
 - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
